<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <RootNamespace>DeathNote</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeathNote.Domain.Shared\DeathNote.Domain.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Authorization" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Account.Application.Contracts" Version="$(AbpVersion)" />
  </ItemGroup>
</Project>
